prompt --application/set_environment
set define off verify off feedback off
whenever sqlerror exit sql.sqlcode rollback
--------------------------------------------------------------------------------
--
-- Oracle APEX export file
--
-- You should run this script using a SQL client connected to the database as
-- the owner (parsing schema) of the application or as a database user with the
-- APEX_ADMINISTRATOR_ROLE role.
--
-- This export file has been automatically generated. Modifying this file is not
-- supported by Oracle and can lead to unexpected application and/or instance
-- behavior now or in the future.
--
-- NOTE: Calls to apex_application_install override the defaults below.
--
--------------------------------------------------------------------------------
begin
wwv_flow_imp.import_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.16'
,p_default_workspace_id=>7653920733150515
,p_default_application_id=>152
,p_default_id_offset=>20927383597185500
,p_default_owner=>'AGENTECH'
);
end;
/
 
prompt APPLICATION 152 - AGENTECH - GENERAL
--
-- Application Export:
--   Application:     152
--   Name:            AGENTECH - GENERAL
--   Exported By:     LUIS
--   Flashback:       0
--   Export Type:     Page Export
--   Manifest
--     PAGE: 746
--   Manifest End
--   Version:         24.2.16
--   Instance ID:     7653701839583073
--

begin
null;
end;
/
prompt --application/pages/delete_00746
begin
wwv_flow_imp_page.remove_page (p_flow_id=>wwv_flow.g_flow_id, p_page_id=>746);
end;
/
prompt --application/pages/page_00746
begin
wwv_flow_imp_page.create_page(
 p_id=>746
,p_name=>'HISTORIAL_WSP'
,p_alias=>'HISTORIAL-WSP'
,p_step_title=>'HISTORIAL_WSP'
,p_autocomplete_on_off=>'OFF'
,p_javascript_file_urls=>'#APP_FILES#CRM.JS'
,p_css_file_urls=>wwv_flow_string.join(wwv_flow_t_varchar2(
'https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css',
'#APP_FILES#crm#MIN#.css'))
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'#waCrmContainer {',
'  padding: 0 !important;',
'  margin: 0 !important;',
'  width: 100% !important;',
'}',
'',
'#waCrmContainer > div {',
'  display: flex !important;',
'  height: calc(100vh - 120px) !important;',
'  min-height: 520px !important;',
'  overflow: hidden !important;',
'  width: 100% !important;',
'}',
'',
'.wa-nav-sidebar {',
'  height: 100% !important;',
'  flex-shrink: 0 !important;',
'  align-self: stretch !important;',
'}',
'',
'.wa-crm-wrapper {',
'  flex: 1 !important;',
'  min-width: 0 !important;',
'  height: 100% !important;',
'  max-height: none !important;',
'  border-radius: 0 12px 12px 0 !important;',
'}',
'',
'.page-746 .t-Body-contentInner .container {',
'  padding-left: 0 !important;',
'  padding-right: 0 !important;',
'  max-width: 100% !important;',
'}',
'',
'.page-746 .t-Body-contentInner .row {',
'  margin-left: 0 !important;',
'  margin-right: 0 !important;',
'}',
'',
'.page-746 .t-Body-contentInner .col,',
'.page-746 .t-Body-contentInner [class*="col-"] {',
'  padding-left: 0 !important;',
'  padding-right: 0 !important;',
'}'))
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'11'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(189179413507998011)
,p_plug_name=>'CONTENEDOR PRINCIPAL'
,p_region_name=>'waCrmContainer'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(224769647651273381)
,p_plug_display_sequence=>20
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<div style="display:flex">',
'',
'  <div class="wa-nav-sidebar">',
'    <div class="wa-nav-logo"><i class="ti ti-message-2"></i></div>',
'    <div class="wa-nav-item active"><i class="ti ti-message-circle"></i></div>',
'    <div class="wa-nav-item"><i class="ti ti-chart-bar"></i></div>',
'    <div class="wa-nav-item"><i class="ti ti-users"></i></div>',
'    <div class="wa-nav-item"><i class="ti ti-bolt"></i></div>',
'    <div class="wa-nav-spacer"></div>',
'    <div class="wa-nav-bottom">',
'      <div class="wa-nav-item"><i class="ti ti-bell"></i><div class="wa-nav-notif"></div></div>',
'      <div class="wa-nav-item"><i class="ti ti-settings"></i></div>',
'    </div>',
'  </div>',
'',
'  <div class="wa-crm-wrapper">',
'',
unistr('    <!-- \2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550 PANEL IZQUIERDO \2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550 -->'),
'    <div class="wa-panel-left" id="waPanelLeft">',
'',
'      <div class="wa-left-header">',
'        <span class="wh-title">',
'          Conversaciones',
'          <span class="wa-conv-count-badge" id="waConvCountBadge">0</span>',
'        </span>',
'        <div class="wh-icons">',
unistr('          <i class="ti ti-edit" title="Nueva conversaci\00F3n"></i>'),
'          <i class="ti ti-layout-sidebar-left-collapse" id="waBtnCollapseLeft"></i>',
'        </div>',
'      </div>',
'',
'      <div class="wa-left-body">',
'',
'        <div class="wa-search-wrap">',
'          <i class="ti ti-search"></i>',
unistr('          <input type="text" id="waSearchInput" placeholder="Buscar conversaci\00F3n...">'),
'          <div class="wa-filter-icon"><i class="ti ti-adjustments-horizontal" style="font-size:15px"></i></div>',
'        </div>',
'',
'        <div class="wa-filter-bar">',
'          <button class="active" data-filter="todas">',
'            Todas <span class="wa-filter-count" id="fcTodas" style="background:var(--crm-blue)">0</span>',
'          </button>',
'          <button data-filter="noleidas">',
unistr('            No le\00EDdas <span class="wa-filter-count" id="fcNoleidas">0</span>'),
'          </button>',
'          <button data-filter="bot">',
'            Bot <span class="wa-filter-count" id="fcBot">0</span>',
'          </button>',
'          <button data-filter="asignadas">',
'            Asig. <span class="wa-filter-count" id="fcAsignadas">0</span>',
'          </button>',
'        </div>',
'',
'        <div class="wa-conv-list" id="waConvList"></div>',
'',
'      </div>',
'',
'      <div class="wa-mini-list" id="waMiniList"></div>',
'',
'      <div class="wa-day-summary" id="waDaySummary">',
'        <div class="wa-day-summary-header">',
unistr('          <span class="wa-day-summary-title">Resumen del d\00EDa</span>'),
'          <a class="wa-day-summary-link">',
'            Ver reporte <i class="ti ti-arrow-right" style="font-size:11px"></i>',
'          </a>',
'        </div>',
'        <div class="wa-day-stats">',
'          <div class="wa-day-stat">',
'            <i class="ti ti-message-2" style="color:#3b82f6"></i>',
'            <div>',
unistr('              <span class="wa-day-stat-val" id="dsTotalConv">\2014</span>'),
'              <span class="wa-day-stat-lbl">Conversaciones</span>',
'            </div>',
'          </div>',
'          <div class="wa-day-stat">',
'            <i class="ti ti-circle-check" style="color:#22c55e"></i>',
'            <div>',
unistr('              <span class="wa-day-stat-val" id="dsResueltas">\2014</span>'),
'              <span class="wa-day-stat-lbl">Resueltas</span>',
'            </div>',
'          </div>',
'          <div class="wa-day-stat">',
'            <i class="ti ti-clock" style="color:#f59e0b"></i>',
'            <div>',
unistr('              <span class="wa-day-stat-val" id="dsPendientes">\2014</span>'),
'              <span class="wa-day-stat-lbl">Pendientes</span>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'',
'    </div>',
'',
unistr('    <!-- \2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550 PANEL CENTRO \2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550 -->'),
'    <div class="wa-panel-center" id="waPanelCenter">',
'',
'      <div class="wa-empty-chat" id="waEmptyChat">',
'        <i class="ti ti-message-2"></i>',
unistr('        <p>Seleccion\00E1 una conversaci\00F3n</p>'),
'      </div>',
'',
'      <div id="waChatContent" style="display:none;flex:1;flex-direction:column;overflow:hidden">',
'',
'        <div class="wa-chat-header">',
'          <div class="wch-av" id="wchAv"></div>',
'          <div class="wch-info">',
'            <div class="wch-name" id="wchName"></div>',
'            <div class="wch-sub"  id="wchSub"></div>',
'          </div>',
'          <div class="wch-acts">',
'            <i class="ti ti-user-plus"  title="Asignar"></i>',
'            <i class="ti ti-tag"        title="Etiquetar"></i>',
'            <i class="ti ti-layout-sidebar-right-collapse" id="waBtnCollapseRight"></i>',
'            <i class="ti ti-dots-vertical"></i>',
'          </div>',
'        </div>',
'',
'        <div class="wa-status-chips" id="waStatusChips">',
'          <span class="wa-chip wa-chip-green"  id="chipEstado"><i class="ti ti-circle-check"></i>Activa</span>',
'          <span class="wa-chip wa-chip-amber"  id="chipAsignado"><i class="ti ti-user"></i>Sin asignar</span>',
'          <span class="wa-chip wa-chip-blue"   id="chipTipo"><i class="ti ti-sparkles"></i>Cliente nuevo</span>',
'        </div>',
'',
'        <div class="wa-info-strip" id="waInfoStrip" style="display:none">',
'          <div class="wis-item"><i class="ti ti-calendar"></i><span id="wisInicio"></span></div>',
unistr('          <span class="wis-sep">\00B7</span>'),
'          <div class="wis-item"><i class="ti ti-clock"></i><span id="wisHora"></span></div>',
unistr('          <span class="wis-sep">\00B7</span>'),
'          <select class="wa-status-quick" id="wisEstado">',
'            <option>ACTIVA</option>',
'            <option>PENDIENTE</option>',
'            <option>CERRADA</option>',
'          </select>',
'        </div>',
'',
'        <div class="wa-messages-area" id="waMensajesArea"></div>',
'',
'        <div class="wa-messages-area" id="waNotasArea" style="display:none;background:#fffbeb"></div>',
'',
'        <div class="wa-input-area">',
'          <div class="wa-msg-tabs">',
'            <button type="button" class="wa-msg-tab active" data-tab="mensaje">Mensaje</button>',
'            <button type="button" class="wa-msg-tab" data-tab="nota">Nota interna</button>',
'            <button type="button" class="wa-msg-tab" data-tab="plantilla">Plantilla</button>',
'          </div>',
'          <div class="wa-composer">',
'            <button type="button" class="wa-icon-btn"><i class="ti ti-paperclip"></i></button>',
'            <button type="button" class="wa-icon-btn"><i class="ti ti-mood-smile"></i></button>',
'            <button type="button" class="wa-icon-btn"><i class="ti ti-bolt"></i></button>',
'            <textarea id="waTextarea" placeholder="Escribe un mensaje..."></textarea>',
'            <span class="wa-char-count" id="waCharCount">0/2000</span>',
'            <button type="button" class="wa-send-btn" id="waBtnSend"><i class="ti ti-send"></i></button>',
'          </div>',
'        </div>',
'',
'      </div>',
'    </div>',
'',
unistr('    <!-- \2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550 PANEL DERECHO \2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550\2550 -->'),
'    <div class="wa-panel-right" id="waPanelRight">',
'',
'      <div class="wa-acc-section">',
'        <div class="wa-acc-header" onclick="waToggleAcc(this)">',
'          <span class="wa-acc-title"><i class="ti ti-user"></i>Contacto</span>',
'          <i class="ti ti-chevron-down wa-acc-arrow open"></i>',
'        </div>',
'        <div class="wa-acc-body open">',
'          <div class="wa-acc-inner" id="waAccContacto">',
unistr('            <div class="wa-sp-val"><i class="ti ti-phone"></i><span id="spTelefono">\2014</span></div>'),
unistr('            <div class="wa-sp-val"><i class="ti ti-hash"></i><span id="spConvId">\2014</span></div>'),
unistr('            <div class="wa-sp-val"><i class="ti ti-calendar"></i><span id="spFechaInicio">\2014</span></div>'),
'            <a class="wa-open-wa-link" id="spWhatsAppLink" href="#" target="_blank">',
'              <i class="ti ti-brand-whatsapp"></i>Abrir en WhatsApp',
'            </a>',
'          </div>',
'        </div>',
'      </div>',
'',
'      <div class="wa-acc-section">',
'        <div class="wa-acc-header" onclick="waToggleAcc(this)">',
'          <span class="wa-acc-title"><i class="ti ti-chart-bar"></i>Resumen</span>',
'          <i class="ti ti-chevron-down wa-acc-arrow open"></i>',
'        </div>',
'        <div class="wa-acc-body open">',
'          <div class="wa-metrics-grid">',
'            <div class="wa-metric-card">',
'              <i class="ti ti-message-2"></i>',
unistr('              <div class="wa-metric-n" id="metMensajes">\2014</div>'),
'              <div class="wa-metric-l">Mensajes</div>',
'            </div>',
'            <div class="wa-metric-card">',
'              <i class="ti ti-pencil"></i>',
unistr('              <div class="wa-metric-n" id="metNotas">\2014</div>'),
'              <div class="wa-metric-l">Notas</div>',
'            </div>',
'            <div class="wa-metric-card">',
'              <i class="ti ti-paperclip"></i>',
unistr('              <div class="wa-metric-n" id="metAdjuntos">\2014</div>'),
'              <div class="wa-metric-l">Adjuntos</div>',
'            </div>',
'            <div class="wa-metric-card">',
'              <i class="ti ti-template"></i>',
unistr('              <div class="wa-metric-n" id="metPlantillas">\2014</div>'),
'              <div class="wa-metric-l">Plantillas</div>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'',
'      <div class="wa-acc-section">',
'        <div class="wa-acc-header" onclick="waToggleAcc(this)">',
unistr('          <span class="wa-acc-title"><i class="ti ti-user-check"></i>Asignaci\00F3n</span>'),
'          <i class="ti ti-chevron-down wa-acc-arrow open"></i>',
'        </div>',
'        <div class="wa-acc-body open">',
'          <div class="wa-acc-inner">',
'            <div class="wa-sp-label">Agente</div>',
'            <select class="wa-sp-select" id="spAgente">',
'              <option value="">Sin asignar</option>',
'            </select>',
'            <button class="wa-sp-btn wa-sp-btn-primary" onclick="waAsignarAgente()">',
'              <i class="ti ti-user-check"></i>Asignar',
'            </button>',
unistr('            <!-- Bloque Estado \2014 solo visible para admins (rol 1) -->'),
'            <div id="waEstadoBloque">',
'              <div class="wa-sp-label" style="margin-top:10px">Estado</div>',
'              <select class="wa-sp-select" id="spEstado">',
'                <option>ACTIVA</option>',
'                <option>PENDIENTE</option>',
'                <option>CERRADA</option>',
'              </select>',
'              <button class="wa-sp-btn wa-sp-btn-secondary" onclick="waActualizarEstado()">',
'                <i class="ti ti-refresh"></i>Actualizar estado',
'              </button>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'',
unistr('      <!-- \2550\2550\2550 ACCIONES R\00C1PIDAS \2550\2550\2550 -->'),
'      <div class="wa-acc-section">',
'        <div class="wa-acc-header" onclick="waToggleAcc(this)">',
unistr('          <span class="wa-acc-title"><i class="ti ti-bolt"></i>Acciones r\00E1pidas</span>'),
'          <i class="ti ti-chevron-down wa-acc-arrow open"></i>',
'        </div>',
'        <div class="wa-acc-body open">',
'          <div class="wa-action-list" id="waAccionesLista">',
unistr('            <!-- Bot\00F3n transferir \2014 abre el panel inline -->'),
'            <div class="wa-action-item" onclick="waAbrirTransferencia()">',
unistr('              <i class="ti ti-arrows-exchange"></i>Transferir conversaci\00F3n'),
'            </div>',
'            <div class="wa-action-item" onclick="waMarcarPendiente()">',
'              <i class="ti ti-clock"></i>Marcar como pendiente',
'            </div>',
'            <div class="wa-action-item danger" onclick="waCerrarConv()">',
unistr('              <i class="ti ti-circle-x"></i>Cerrar conversaci\00F3n'),
'            </div>',
'          </div>',
'',
unistr('          <!-- Panel inline transferencia (modelo 3) \2014 oculto por defecto -->'),
'          <div id="waTransferPanel" style="display:none;padding:0 16px 12px">',
'',
'            <!-- Agente actual -->',
'            <div style="display:flex;align-items:center;gap:8px;padding:7px 8px;background:var(--color-bg-2,#f1f5f9);border-radius:8px;margin-bottom:10px">',
'              <div id="trAvActual" style="width:28px;height:28px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:10px;font-weight:600;flex-shrink:0;background:#dbeafe;color:#1e40af"></div>',
'              <div style="flex:1">',
unistr('                <div style="font-size:11px;font-weight:500;color:var(--color-text)" id="trNombreActual">\2014</div>'),
'                <div style="font-size:10px;color:#94a3b8">Agente actual</div>',
'              </div>',
'              <i class="ti ti-chevron-right" style="font-size:13px;color:#94a3b8"></i>',
'            </div>',
'',
'            <!-- Label -->',
'            <div style="font-size:10px;font-weight:500;color:#94a3b8;text-transform:uppercase;letter-spacing:.05em;margin-bottom:6px">Transferir a</div>',
'',
unistr('            <!-- Grid de agentes \2014 se llena din\00E1micamente -->'),
'            <div id="trAgentesGrid" style="display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-bottom:8px">',
'              <div style="text-align:center;padding:12px;font-size:11px;color:#94a3b8;grid-column:span 2">Cargando agentes...</div>',
'            </div>',
'',
'            <!-- Nota opcional -->',
'            <textarea id="trNota" rows="2"',
'              placeholder="Nota para el agente (opcional)..."',
'              style="width:100%;padding:6px 8px;border:0.5px solid #e2e8f0;border-radius:8px;font-size:11px;background:transparent;color:var(--color-text);resize:none;margin-bottom:6px;outline:none"></textarea>',
'',
'            <!-- Botones -->',
'            <div style="display:flex;gap:6px">',
'              <button type="button" onclick="waCerrarTransferencia()"',
'                style="flex:1;padding:7px;border-radius:8px;font-size:11px;font-weight:500;border:0.5px solid #e2e8f0;background:transparent;cursor:pointer;color:var(--color-text)">',
'                Cancelar',
'              </button>',
'              <button type="button" onclick="waConfirmarTransferencia()"',
'                style="flex:2;padding:7px;border-radius:8px;font-size:11px;font-weight:500;border:none;background:#185FA5;color:#fff;cursor:pointer;display:flex;align-items:center;justify-content:center;gap:5px">',
'                <i class="ti ti-arrows-exchange" style="font-size:12px"></i>Confirmar transferencia',
'              </button>',
'            </div>',
'',
'          </div>',
'        </div>',
'      </div>',
'',
'      <div class="wa-acc-section">',
'        <div class="wa-acc-header" onclick="waToggleAcc(this)">',
'          <span class="wa-acc-title">',
'            <i class="ti ti-pencil"></i>Notas internas',
'            <span class="wa-acc-count" id="notasCount">0</span>',
'          </span>',
'          <i class="ti ti-chevron-down wa-acc-arrow"></i>',
'        </div>',
'        <div class="wa-acc-body">',
'          <div class="wa-acc-inner" id="waAccNotas">',
'            <div style="font-size:11px;color:#9ca3af;text-align:center;padding:8px 0">Sin notas</div>',
'          </div>',
'          <div style="padding:0 16px 12px">',
'            <textarea id="waNotaTexto" rows="3"',
unistr('              placeholder="Escrib\00ED una nota interna..."></textarea>'),
'            <button type="button" onclick="waGuardarNota()"',
'              class="wa-sp-btn wa-sp-btn-secondary" style="margin-top:6px">',
'              <i class="ti ti-device-floppy"></i>Guardar nota',
'            </button>',
'          </div>',
'        </div>',
'      </div>',
'',
'      <div class="wa-acc-section">',
'        <div class="wa-acc-header" onclick="waToggleAcc(this)">',
'          <span class="wa-acc-title">',
unistr('            <i class="ti ti-message-bolt"></i>Respuesta r\00E1pidas'),
'            <span class="wa-acc-count" id="rpCount">4</span>',
'          </span>',
'          <i class="ti ti-chevron-down wa-acc-arrow"></i>',
'        </div>',
'        <div class="wa-acc-body">',
'          <div class="wa-acc-inner" id="waAccRapidas">',
unistr('            <div class="wa-action-item" onclick="waUsarRapida(this)"><i class="ti ti-bolt"></i>Bienvenida est\00E1ndar</div>'),
'            <div class="wa-action-item" onclick="waUsarRapida(this)"><i class="ti ti-bolt"></i>Consulta recibida</div>',
'            <div class="wa-action-item" onclick="waUsarRapida(this)"><i class="ti ti-bolt"></i>Derivar a ventas</div>',
unistr('            <div class="wa-action-item" onclick="waUsarRapida(this)"><i class="ti ti-bolt"></i>Cierre de conversaci\00F3n</div>'),
'          </div>',
'        </div>',
'      </div>',
'',
'      <div class="wa-acc-section">',
'        <div class="wa-acc-header" onclick="waToggleAcc(this)">',
'          <span class="wa-acc-title">',
'            <i class="ti ti-paperclip"></i>Adjuntos',
'            <span class="wa-acc-count" id="adjCount">0</span>',
'          </span>',
'          <i class="ti ti-chevron-down wa-acc-arrow"></i>',
'        </div>',
'        <div class="wa-acc-body">',
'          <div class="wa-acc-inner" id="waAccAdjuntos">',
'            <div style="font-size:11px;color:#9ca3af;text-align:center;padding:8px 0">Sin adjuntos</div>',
'          </div>',
'          <div style="padding:0 16px 12px">',
'            <label for="waFileInput" class="wa-upload-label">',
'              <i class="ti ti-upload" style="font-size:18px"></i>',
unistr('              <span id="waFileLabel">Seleccion\00E1 un archivo</span>'),
'            </label>',
'            <input type="file" id="waFileInput" style="display:none" onchange="waPreviewFile(this)">',
'            <button onclick="waSubirAdjunto()" id="waBtnSubir"',
'              class="wa-sp-btn wa-sp-btn-secondary" style="margin-top:6px;display:none">',
'              <i class="ti ti-upload"></i>Subir archivo',
'            </button>',
'          </div>',
'        </div>',
'      </div>',
'',
'    </div>',
'',
'  </div>',
'',
'</div>'))
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(189180925488998026)
,p_process_sequence=>10
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'WA_GET_CONVERSACIONES'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'  l_json       CLOB        := ''['';',
'  l_sep        VARCHAR2(1) := '''';',
'  l_id_rol     NUMBER      := 0;',
'  l_es_admin   VARCHAR2(1) := ''N'';',
'  l_total      NUMBER := 0;',
'  l_noleidas   NUMBER := 0;',
'  l_bot        NUMBER := 0;',
'  l_asignadas  NUMBER := 0;',
'  l_resueltas  NUMBER := 0;',
'  l_pendientes NUMBER := 0;',
'BEGIN',
'  -- Verificar si el usuario logueado es admin (ID_ROL = 1)',
'  BEGIN',
'    SELECT id_rol',
'    INTO   l_id_rol',
'    FROM   t_usuarios',
'    WHERE  id_usuario = V(''APP_USER'')',
'      AND  rownum     = 1;',
'  EXCEPTION',
'    WHEN NO_DATA_FOUND THEN l_id_rol := 0;',
'  END;',
'',
'  IF l_id_rol = 1 THEN',
'    l_es_admin := ''S'';',
'  END IF;',
'',
'  -- Conteos globales (respetan el mismo filtro)',
'  SELECT',
'    COUNT(*),',
'    SUM(CASE WHEN noleidos > 0                                        THEN 1 ELSE 0 END),',
'    SUM(CASE WHEN usuario_asignado LIKE ''BOT%''                        THEN 1 ELSE 0 END),',
'    SUM(CASE WHEN usuario_asignado NOT IN (''SIN ASIGNAR'')             THEN 1 ELSE 0 END),',
'    SUM(CASE WHEN estado = ''CERRADA''                                  THEN 1 ELSE 0 END),',
'    SUM(CASE WHEN estado = ''PENDIENTE''                                THEN 1 ELSE 0 END)',
'  INTO l_total, l_noleidas, l_bot, l_asignadas, l_resueltas, l_pendientes',
'  FROM (',
'    SELECT',
'      c.estado,',
'      NVL(c.usuario_asignado, ''SIN ASIGNAR'') AS usuario_asignado,',
'      (SELECT COUNT(*)',
'       FROM   t_whatsapp_mensajes m',
'       WHERE  m.id_conversacion = c.id_conversacion',
'         AND  m.leido           = ''N''',
'         AND  m.direccion       = ''ENTRADA'') AS noleidos',
'    FROM t_whatsapp_conversaciones c',
'    INNER JOIN (',
'      SELECT telefono, MAX(id_conversacion) AS max_id',
'      FROM   t_whatsapp_conversaciones',
'      GROUP BY telefono',
'    ) ult ON ult.telefono = c.telefono',
'         AND ult.max_id   = c.id_conversacion',
'    WHERE (',
'  l_es_admin = ''S''                                              -- admin ve todo incluso CERRADAS',
'  OR (',
unistr('    c.estado != ''CERRADA''                                       -- t\00E9cnicos NO ven CERRADAS'),
'    AND (',
'      NVL(c.usuario_asignado, ''SIN ASIGNAR'') = ''SIN ASIGNAR''',
'      OR c.usuario_asignado = V(''APP_USER'')',
'    )',
'  )',
')',
'  );',
'',
'  -- Primer objeto: stats',
'  l_json := l_json',
'    || ''{"id":-1''',
'    || '',"_stats":true''',
'    || '',"total":''      || l_total',
'    || '',"noleidas":''   || l_noleidas',
'    || '',"bot":''        || l_bot',
'    || '',"asignadas":''  || l_asignadas',
'    || '',"resueltas":''  || l_resueltas',
'    || '',"pendientes":'' || l_pendientes',
'    || '',"es_admin":"''  || l_es_admin || ''"''',
'    || ''}'';',
'  l_sep := '','';',
'',
'  -- Conversaciones filtradas',
'  FOR r IN (',
'    SELECT',
'      c.id_conversacion,',
'      c.telefono,',
'      c.estado,',
'      NVL(c.usuario_asignado, ''SIN ASIGNAR'')  AS usuario_asignado,',
'      TO_CHAR(c.ultimo_mensaje, ''HH24:MI'')     AS hora_formato,',
'      TO_CHAR(c.fecha_alta,     ''DD/MM/YYYY'')  AS fecha_inicio_fmt,',
'      UPPER(SUBSTR(c.telefono, -4, 2))         AS iniciales,',
'      CASE c.estado',
'        WHEN ''ACTIVA''    THEN ''wa-dot-green''',
'        WHEN ''PENDIENTE'' THEN ''wa-dot-amber''',
'        ELSE ''wa-dot-gray''',
'      END AS dot_class,',
'      CASE',
'        WHEN c.usuario_asignado LIKE ''BOT%'' THEN ''wa-tag-bot''',
'        WHEN c.usuario_asignado IS NULL      THEN ''wa-tag-noassign''',
'        WHEN c.estado = ''CERRADA''            THEN ''wa-tag-closed''',
'        ELSE ''wa-tag-agent''',
'      END AS tag_class,',
'      (SELECT NVL(TO_CHAR(COUNT(*)), ''0'')',
'       FROM   t_whatsapp_mensajes m',
'       WHERE  m.id_conversacion = c.id_conversacion',
'         AND  m.leido           = ''N''',
'         AND  m.direccion       = ''ENTRADA'') AS no_leidos,',
'      (SELECT REPLACE(REPLACE(SUBSTR(m2.mensaje, 1, 40), ''"'', ''''), CHR(10), '' '')',
'       FROM   t_whatsapp_mensajes m2',
'       WHERE  m2.id_mensaje = (',
'         SELECT MAX(m3.id_mensaje)',
'         FROM   t_whatsapp_mensajes m3',
'         WHERE  m3.id_conversacion = c.id_conversacion',
'       )) AS ultimo_texto',
'    FROM t_whatsapp_conversaciones c',
'    INNER JOIN (',
'      SELECT telefono, MAX(id_conversacion) AS max_id',
'      FROM   t_whatsapp_conversaciones',
'      GROUP BY telefono',
'    ) ult ON ult.telefono = c.telefono',
'          AND ult.max_id  = c.id_conversacion',
'    WHERE (',
'  l_es_admin = ''S''                                              -- admin ve todo incluso CERRADAS',
'  OR (',
unistr('    c.estado != ''CERRADA''                                       -- t\00E9cnicos NO ven CERRADAS'),
'    AND (',
'      NVL(c.usuario_asignado, ''SIN ASIGNAR'') = ''SIN ASIGNAR''',
'      OR c.usuario_asignado = V(''APP_USER'')',
'    )',
'  )',
')',
'    ORDER BY c.ultimo_mensaje DESC NULLS LAST',
'  ) LOOP',
'    l_json := l_json || l_sep || ''{''',
'      || ''"id":''         || r.id_conversacion                          || '',''',
'      || ''"telefono":"''  || REPLACE(r.telefono,         ''"'', '''')       || ''",''',
'      || ''"estado":"''    || REPLACE(r.estado,           ''"'', '''')       || ''",''',
'      || ''"asignado":"''  || REPLACE(r.usuario_asignado, ''"'', '''')       || ''",''',
'      || ''"hora":"''      || REPLACE(r.hora_formato,     ''"'', '''')       || ''",''',
'      || ''"inicio":"''    || REPLACE(r.fecha_inicio_fmt, ''"'', '''')       || ''",''',
'      || ''"iniciales":"'' || REPLACE(r.iniciales,        ''"'', '''')       || ''",''',
'      || ''"dot":"''       || r.dot_class                                || ''",''',
'      || ''"tag":"''       || r.tag_class                                || ''",''',
'      || ''"noleidos":"''  || r.no_leidos                                || ''",''',
'      || ''"preview":"''   || REPLACE(NVL(r.ultimo_texto,''''), ''"'', '''''''') || ''"}'';',
'    l_sep := '','';',
'  END LOOP;',
'',
'  l_json := l_json || '']'';',
'  HTP.p(l_json);',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    HTP.p(''[]'');',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>189180925488998026
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(189181009663998027)
,p_process_sequence=>20
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'WA_GET_MENSAJES'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'  l_conv_id   NUMBER := TO_NUMBER(apex_application.g_x01);',
'  l_json      CLOB   := ''['';',
'  l_sep       VARCHAR2(1) := '''';',
'  l_cnt_msg   NUMBER := 0;',
'  l_cnt_notas NUMBER := 0;',
'  l_cnt_adj   NUMBER := 0;',
'BEGIN',
'  UPDATE t_whatsapp_mensajes',
'  SET    leido = ''S''',
'  WHERE  id_conversacion = l_conv_id',
'    AND  direccion       = ''ENTRADA''',
'    AND  leido           = ''N'';',
'',
'  SELECT',
'    SUM(CASE WHEN tipo_mensaje != ''NOTA'' THEN 1 ELSE 0 END),',
'    SUM(CASE WHEN tipo_mensaje  = ''NOTA'' THEN 1 ELSE 0 END)',
'  INTO l_cnt_msg, l_cnt_notas',
'  FROM t_whatsapp_mensajes',
'  WHERE id_conversacion = l_conv_id;',
'',
'  SELECT COUNT(*)',
'  INTO l_cnt_adj',
'  FROM t_whatsapp_adjuntos',
'  WHERE id_conversacion = l_conv_id;',
'',
'  l_json := l_json',
'    || ''{"id_mensaje":-1''',
'    || '',"_metrics":true''',
'    || '',"cnt_mensajes":'' || NVL(l_cnt_msg,   0)',
'    || '',"cnt_notas":''    || NVL(l_cnt_notas, 0)',
'    || '',"cnt_adjuntos":'' || NVL(l_cnt_adj,   0)',
'    || ''}'';',
'  l_sep := '','';',
'',
'  FOR r IN (',
'    SELECT',
'      m.id_mensaje,',
'      REPLACE(REPLACE(NVL(m.mensaje,''''), ''"'', ''''''''), CHR(10), '' '') AS mensaje,',
'      m.direccion,',
'      m.tipo_mensaje,',
'      NVL(m.intencion,    '''') AS intencion,',
'      NVL(m.usuario_alta, '''') AS usuario_alta,',
'      TO_CHAR(m.fecha_mensaje, ''DD/MM/YYYY'') AS fecha,',
'      TO_CHAR(m.fecha_mensaje, ''HH24:MI'')    AS hora,',
'      c.telefono,',
'      NVL(m.media_url,  '''') AS media_url,',
'      NVL(m.media_tipo, '''') AS media_tipo',
'    FROM t_whatsapp_mensajes m',
'    JOIN t_whatsapp_conversaciones c',
'      ON c.id_conversacion = m.id_conversacion',
'    WHERE m.id_conversacion = l_conv_id',
'    ORDER BY m.fecha_mensaje ASC',
'  ) LOOP',
'    l_json := l_json || l_sep || ''{''',
'      || ''"id_mensaje":''    || r.id_mensaje                              || '',''',
'      || ''"mensaje":"''      || REPLACE(r.mensaje,      ''"'', '''''''')        || ''",''',
'      || ''"direccion":"''    || REPLACE(r.direccion,    ''"'', '''')          || ''",''',
'      || ''"tipo_mensaje":"'' || REPLACE(r.tipo_mensaje, ''"'', '''')          || ''",''',
'      || ''"intencion":"''    || REPLACE(r.intencion,    ''"'', '''')          || ''",''',
'      || ''"usuario_alta":"'' || REPLACE(r.usuario_alta, ''"'', '''')          || ''",''',
'      || ''"fecha":"''        || REPLACE(r.fecha,        ''"'', '''')          || ''",''',
'      || ''"hora":"''         || REPLACE(r.hora,         ''"'', '''')          || ''",''',
'      || ''"telefono":"''     || REPLACE(r.telefono,     ''"'', '''')          || ''",''',
'      || ''"media_url":"''    || REPLACE(r.media_url,    ''"'', '''')          || ''",''',
'      || ''"media_tipo":"''   || REPLACE(r.media_tipo,   ''"'', '''')          || ''"}'';',
'    l_sep := '','';',
'  END LOOP;',
'',
'  l_json := l_json || '']'';',
'  HTP.p(l_json);',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    ROLLBACK;',
'    HTP.p(''[]'');',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>189181009663998027
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(189181154942998028)
,p_process_sequence=>30
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'WA_SEND_MENSAJE'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'  l_conv_id     NUMBER         := TO_NUMBER(apex_application.g_x01);',
'  l_mensaje     VARCHAR2(4000) := apex_application.g_x02;',
'  l_tipo        VARCHAR2(30)   := apex_application.g_x03;',
'  l_tel_param   VARCHAR2(20)   := apex_application.g_x04;',
'  l_telefono    VARCHAR2(20);',
'  l_empresa     NUMBER;',
'  l_propietario VARCHAR2(200);',
'  l_next_id     NUMBER;',
'  l_url_node    VARCHAR2(500) := ''https://crmserver.agentech.com.py/enviar-whatsapp'';',
'  l_body        CLOB;',
'  l_response    CLOB;',
'  l_status      NUMBER;',
'BEGIN',
'  SELECT id_empresa, id_propietario, telefono',
'    INTO l_empresa, l_propietario, l_telefono',
'    FROM t_whatsapp_conversaciones',
'   WHERE id_conversacion = l_conv_id;',
'',
'  IF l_telefono IS NULL THEN',
'    l_telefono := l_tel_param;',
'  END IF;',
'',
'  SELECT NVL(MAX(id_mensaje), 0) + 1',
'    INTO l_next_id',
'    FROM t_whatsapp_mensajes;',
'',
'  INSERT INTO t_whatsapp_mensajes (',
'    id_mensaje, id_empresa, id_propietario, id_conversacion,',
'    direccion, mensaje, tipo_mensaje,',
'    leido, respondido, fecha_mensaje, usuario_alta, fecha_alta',
'  ) VALUES (',
'    l_next_id, l_empresa, l_propietario, l_conv_id,',
'    ''SALIDA'', l_mensaje, l_tipo,',
'    ''S'', ''S'', SYSDATE, :APP_USER, SYSDATE',
'  );',
'',
'  UPDATE t_whatsapp_conversaciones',
'     SET ultimo_mensaje = SYSDATE',
'   WHERE id_conversacion = l_conv_id;',
'',
'  COMMIT;',
'',
'  IF l_tipo != ''NOTA'' THEN',
'    apex_json.initialize_clob_output;',
'    apex_json.open_object;',
'    apex_json.write(''telefono'', l_telefono);',
'    apex_json.write(''mensaje'', l_mensaje);',
'    apex_json.close_object;',
'    l_body := apex_json.get_clob_output;',
'    apex_json.free_output;',
'',
'    apex_web_service.g_request_headers.delete;',
'    apex_web_service.g_request_headers(1).name  := ''Content-Type'';',
'    apex_web_service.g_request_headers(1).value := ''application/json'';',
'',
'    l_response := apex_web_service.make_rest_request(',
'      p_url         => l_url_node,',
'      p_http_method => ''POST'',',
'      p_body        => l_body',
'    );',
'',
'    l_status := apex_web_service.g_status_code;',
'  END IF;',
'',
'  apex_json.open_object;',
'  apex_json.write(''success'', true);',
'  apex_json.write(''status'', NVL(l_status, 0));',
'  apex_json.write(''telefono_usado'', l_telefono);',
'  apex_json.write(''url_node'', l_url_node);',
'  apex_json.write(''body_enviado'', l_body);',
'  apex_json.write(''response_node'', l_response);',
'  apex_json.close_object;',
'',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    ROLLBACK;',
'    apex_json.open_object;',
'    apex_json.write(''success'', false);',
'    apex_json.write(''error'', SQLERRM);',
'    apex_json.close_object;',
'END;',
''))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>189181154942998028
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(189181258307998029)
,p_process_sequence=>40
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'WA_UPDATE_CONV'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'  l_conv_id NUMBER        := TO_NUMBER(apex_application.g_x01);',
'  l_valor   VARCHAR2(200) := apex_application.g_x02;',
'  l_campo   VARCHAR2(20)  := apex_application.g_x03;',
'BEGIN',
'  IF l_campo = ''AGENTE'' THEN',
'    UPDATE t_whatsapp_conversaciones',
'    SET usuario_asignado = l_valor,',
'        usuario_mod      = :APP_USER,',
'        fecha_mod        = SYSDATE',
'    WHERE id_conversacion = l_conv_id;',
'  ELSIF l_campo = ''ESTADO'' THEN',
'    UPDATE t_whatsapp_conversaciones',
'    SET estado      = l_valor,',
'        usuario_mod = :APP_USER,',
'        fecha_mod   = SYSDATE',
'    WHERE id_conversacion = l_conv_id;',
'  END IF;',
'  COMMIT;',
'  apex_json.open_object;',
'  apex_json.write(''status'', ''ok'');',
'  apex_json.close_object;',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    ROLLBACK;',
'    apex_json.open_object;',
'    apex_json.write(''status'', ''error'');',
'    apex_json.write(''msg'', SQLERRM);',
'    apex_json.close_object;',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>189181258307998029
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(189181340817998030)
,p_process_sequence=>50
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'WA_GET_USUARIOS'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'BEGIN',
'  apex_json.open_array;',
'  FOR r IN (',
'    SELECT id_usuario,',
'           REPLACE(REPLACE(REPLACE(REPLACE(',
'             NVL(desc_usuario, id_usuario),',
'             CHR(10),'' ''), CHR(13),'' ''), CHR(9),'' ''), ''"'', '''''''') AS desc_limpio',
'    FROM t_usuarios',
'    WHERE activo = ''S''',
'    AND id_propietario = :P0_PROPIETARIO_ID',
'    ORDER BY desc_usuario',
'  ) LOOP',
'    apex_json.open_object;',
'    apex_json.write(''id'',     r.id_usuario);',
'    apex_json.write(''nombre'', r.desc_limpio);',
'    apex_json.close_object;',
'  END LOOP;',
'  apex_json.close_array;',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    apex_json.open_array;',
'    apex_json.close_array;',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>189181340817998030
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(189181459751998031)
,p_process_sequence=>60
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'WA_GET_ADJUNTOS'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'  l_conv_id NUMBER := TO_NUMBER(apex_application.g_x01);',
'BEGIN',
'  apex_json.open_array;',
'',
'  FOR r IN (',
'    SELECT id_adjunto,',
'           REPLACE(REPLACE(nombre_archivo, ''"'', ''''''''), CHR(10), '' '') AS nombre_archivo,',
'           NVL(usuario_alta, '''') AS usuario_alta,',
'           TO_CHAR(fecha_alta, ''DD/MM HH24:MI'') AS fecha_fmt,',
'           NVL(media_url, '''') AS media_url,',
'           NVL(media_tipo, '''') AS media_tipo',
'    FROM t_whatsapp_adjuntos',
'    WHERE id_conversacion = l_conv_id',
'    ORDER BY fecha_alta DESC',
'  ) LOOP',
'    apex_json.open_object;',
'    apex_json.write(''id'',         r.id_adjunto);',
'    apex_json.write(''nombre'',     r.nombre_archivo);',
'    apex_json.write(''usuario'',    r.usuario_alta);',
'    apex_json.write(''fecha'',      r.fecha_fmt);',
'    apex_json.write(''media_url'',  r.media_url);',
'    apex_json.write(''media_tipo'', r.media_tipo);',
'    apex_json.close_object;',
'  END LOOP;',
'',
'  apex_json.close_array;',
'',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    apex_json.open_array;',
'    apex_json.close_array;',
'END;',
''))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>189181459751998031
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(189181541256998032)
,p_process_sequence=>70
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'WA_SAVE_ADJUNTO'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'  l_conv_id  NUMBER        := TO_NUMBER(apex_application.g_x01);',
'  l_nombre   VARCHAR2(500) := apex_application.g_x02;',
'  l_mime     VARCHAR2(200) := apex_application.g_x03;',
'  l_base64   CLOB          := apex_application.g_x04;',
'  l_blob     BLOB;',
'  l_next_id  NUMBER;',
'  l_empresa  NUMBER;',
'  l_raw      RAW(32767);',
'  l_amt      INTEGER := 7700;',
'  l_offset   INTEGER := 1;',
'  l_len      INTEGER;',
'BEGIN',
'  SELECT id_empresa INTO l_empresa',
'  FROM t_whatsapp_conversaciones',
'  WHERE id_conversacion = l_conv_id;',
'',
'  SELECT NVL(MAX(id_adjunto), 0) + 1',
'  INTO l_next_id',
'  FROM t_whatsapp_adjuntos;',
'',
'  -- Convertir base64 a BLOB manualmente',
'  DBMS_LOB.CREATETEMPORARY(l_blob, TRUE);',
'  l_len := DBMS_LOB.GETLENGTH(l_base64);',
'',
'  WHILE l_offset <= l_len LOOP',
'    l_raw := UTL_ENCODE.BASE64_DECODE(',
'      UTL_RAW.CAST_TO_RAW(DBMS_LOB.SUBSTR(l_base64, l_amt, l_offset))',
'    );',
'    DBMS_LOB.WRITEAPPEND(l_blob, UTL_RAW.LENGTH(l_raw), l_raw);',
'    l_offset := l_offset + l_amt;',
'  END LOOP;',
'',
'  INSERT INTO t_whatsapp_adjuntos (',
'    id_adjunto, id_empresa, id_conversacion,',
'    nombre_archivo, tipo_mime, tamano,',
'    contenido, usuario_alta, fecha_alta',
'  ) VALUES (',
'    l_next_id, l_empresa, l_conv_id,',
'    l_nombre, l_mime, DBMS_LOB.GETLENGTH(l_blob),',
'    l_blob, :APP_USER, SYSDATE',
'  );',
'',
'  COMMIT;',
'  apex_json.open_object;',
'  apex_json.write(''status'', ''ok'');',
'  apex_json.close_object;',
'',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    ROLLBACK;',
'    apex_json.open_object;',
'    apex_json.write(''status'', ''error'');',
'    apex_json.write(''msg'', SQLERRM);',
'    apex_json.close_object;',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>189181541256998032
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(189181663898998033)
,p_process_sequence=>80
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'WA_GET_NOTAS'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'  l_conv_id NUMBER := TO_NUMBER(apex_application.g_x01);',
'BEGIN',
'  apex_json.open_array;',
'  FOR r IN (',
'    SELECT m.id_mensaje,',
'           REPLACE(REPLACE(REPLACE(REPLACE(',
'             NVL(m.mensaje,''''),',
'             CHR(10),'' ''), CHR(13),'' ''), CHR(9),'' ''), ''"'', '''''''') AS mensaje,',
'           NVL(m.usuario_alta,'''') AS usuario_alta,',
'           TO_CHAR(m.fecha_mensaje,''DD/MM/YYYY HH24:MI'') AS fecha_hora',
'    FROM t_whatsapp_mensajes m',
'    WHERE m.id_conversacion = l_conv_id',
'    AND m.tipo_mensaje = ''NOTA''',
'    ORDER BY m.fecha_mensaje ASC',
'  ) LOOP',
'    apex_json.open_object;',
'    apex_json.write(''id'',      r.id_mensaje);',
'    apex_json.write(''mensaje'', r.mensaje);',
'    apex_json.write(''usuario'', r.usuario_alta);',
'    apex_json.write(''fecha'',   r.fecha_hora);',
'    apex_json.close_object;',
'  END LOOP;',
'  apex_json.close_array;',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    apex_json.open_array;',
'    apex_json.close_array;',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>189181663898998033
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(197549542768371707)
,p_process_sequence=>90
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'WA_FINALIZAR_CONVERSACION'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'  l_conv_id   NUMBER := TO_NUMBER(apex_application.g_x01);',
'  l_telefono  VARCHAR2(30);',
'  l_body      CLOB;',
'  l_response  CLOB;',
'  l_status    NUMBER;',
'BEGIN',
'  SELECT telefono',
'    INTO l_telefono',
'    FROM t_whatsapp_conversaciones',
'   WHERE id_conversacion = l_conv_id;',
'',
'  UPDATE t_whatsapp_conversaciones',
'     SET estado = ''CERRADA'',',
'         usuario_mod = :APP_USER,',
'         fecha_mod = SYSDATE',
'   WHERE id_conversacion = l_conv_id;',
'',
'  apex_json.initialize_clob_output;',
'  apex_json.open_object;',
'  apex_json.write(''telefono'', l_telefono);',
'  apex_json.close_object;',
'  l_body := apex_json.get_clob_output;',
'  apex_json.free_output;',
'',
'  apex_web_service.g_request_headers.delete;',
'  apex_web_service.g_request_headers(1).name  := ''Content-Type'';',
'  apex_web_service.g_request_headers(1).value := ''application/json'';',
'',
'  l_response := apex_web_service.make_rest_request(',
'    p_url         => ''https://crmserver.agentech.com.py/reset-conversation'',',
'    p_http_method => ''POST'',',
'    p_body        => l_body',
'  );',
'',
'  l_status := apex_web_service.g_status_code;',
'',
'  COMMIT;',
'',
'  apex_json.open_object;',
'  apex_json.write(''success'', true);',
'  apex_json.write(''telefono'', l_telefono);',
'  apex_json.write(''status_node'', l_status);',
'  apex_json.write(''response_node'', l_response);',
'  apex_json.close_object;',
'',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    ROLLBACK;',
'    apex_json.open_object;',
'    apex_json.write(''success'', false);',
'    apex_json.write(''error'', SQLERRM);',
'    apex_json.close_object;',
'END;',
''))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>197549542768371707
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(197779119782365024)
,p_process_sequence=>100
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'WA_ASIGNAR_TECNICO'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'  v_id_conv  NUMBER       := TO_NUMBER(apex_application.g_x01);',
'  v_tipo     VARCHAR2(20) := NVL(apex_application.g_x02, ''TECNICO'');',
'  v_usuario  VARCHAR2(100);',
'  v_result   VARCHAR2(200);',
'BEGIN',
'  PR_ASIGNAR_TECNICO(',
'    p_id_conversacion  => v_id_conv,',
'    p_tipo             => v_tipo,',
'    p_id_propietario   => ''AGENTECH'',',
'    p_usuario_asignado => v_usuario,',
'    p_resultado        => v_result',
'  );',
'',
'  IF v_result = ''OK'' THEN',
'    APEX_JSON.OPEN_OBJECT;',
'    APEX_JSON.WRITE(''success'', TRUE);',
'    APEX_JSON.WRITE(''asignado'', v_usuario);',
'    APEX_JSON.WRITE(''mensaje'', ''Asignado a: '' || v_usuario);',
'    APEX_JSON.CLOSE_OBJECT;',
'  ELSIF v_result = ''SIN_DISPONIBLE'' THEN',
'    APEX_JSON.OPEN_OBJECT;',
'    APEX_JSON.WRITE(''success'', FALSE);',
unistr('    APEX_JSON.WRITE(''mensaje'', ''Sin t\00E9cnicos disponibles.'');'),
'    APEX_JSON.CLOSE_OBJECT;',
'  ELSE',
'    APEX_JSON.OPEN_OBJECT;',
'    APEX_JSON.WRITE(''success'', FALSE);',
'    APEX_JSON.WRITE(''mensaje'', v_result);',
'    APEX_JSON.CLOSE_OBJECT;',
'  END IF;',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>197779119782365024
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(197781113828365044)
,p_process_sequence=>110
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'WA_GET_AGENTES_CARGA'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'BEGIN',
'  apex_json.open_array;',
'  FOR r IN (',
'    SELECT u.id_usuario,',
'           REPLACE(REPLACE(NVL(u.desc_usuario, u.id_usuario), CHR(10),'' ''), ''"'', '''''''') AS desc_limpio,',
'           NVL(c.conv_activas, 0) AS conv_activas',
'    FROM t_usuarios u',
'    LEFT JOIN (',
'      SELECT usuario_asignado, COUNT(*) AS conv_activas',
'      FROM   t_whatsapp_conversaciones',
'      WHERE  estado IN (''ACTIVA'',''PENDIENTE'')',
'        AND  usuario_asignado IS NOT NULL',
'        AND  id_propietario = :P0_PROPIETARIO_ID',
'      GROUP BY usuario_asignado',
'    ) c ON c.usuario_asignado = u.id_usuario',
'    WHERE u.activo        = ''S''',
'      AND u.id_propietario = :P0_PROPIETARIO_ID',
'      AND u.id_rol         = 5',
'    ORDER BY NVL(c.conv_activas, 0) ASC, u.desc_usuario ASC',
'  ) LOOP',
'    apex_json.open_object;',
'    apex_json.write(''id'',           r.id_usuario);',
'    apex_json.write(''nombre'',       r.desc_limpio);',
'    apex_json.write(''conv_activas'', r.conv_activas);',
'    apex_json.close_object;',
'  END LOOP;',
'  apex_json.close_array;',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    apex_json.open_array;',
'    apex_json.close_array;',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>197781113828365044
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(197781299036365045)
,p_process_sequence=>120
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'WA_TRANSFERIR_CONV'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'  l_conv_id    NUMBER       := TO_NUMBER(apex_application.g_x01);',
'  l_agente     VARCHAR2(100) := apex_application.g_x02;',
'  l_nota       VARCHAR2(4000):= apex_application.g_x03;',
'  l_agente_ant VARCHAR2(100);',
'  l_id_prop    VARCHAR2(100);',
'  l_id_emp     NUMBER;',
'  l_id_msg     NUMBER;',
'BEGIN',
unistr('  -- Datos actuales de la conversaci\00F3n'),
'  SELECT usuario_asignado, id_propietario, id_empresa',
'    INTO l_agente_ant, l_id_prop, l_id_emp',
'    FROM t_whatsapp_conversaciones',
'   WHERE id_conversacion = l_conv_id;',
'',
'  -- Actualizar agente asignado',
'  UPDATE t_whatsapp_conversaciones',
'     SET usuario_asignado = l_agente,',
'         usuario_mod      = :APP_USER,',
'         fecha_mod        = SYSDATE',
'   WHERE id_conversacion  = l_conv_id;',
'',
'  -- Nota interna de transferencia',
'  SELECT SEQ_WHATSAPP_MENSAJES.NEXTVAL INTO l_id_msg FROM DUAL;',
'',
'  INSERT INTO t_whatsapp_mensajes (',
'    id_mensaje, id_conversacion, id_propietario, id_empresa,',
'    mensaje, direccion, tipo_mensaje,',
'    leido, usuario_alta, fecha_alta',
'  ) VALUES (',
'    l_id_msg, l_conv_id, l_id_prop, l_id_emp,',
unistr('    ''Conversaci\00F3n transferida de '' || NVL(l_agente_ant,''Sin asignar'') || '' \2192 '' || l_agente'),
'    || CASE WHEN l_nota IS NOT NULL THEN ''. Nota: '' || l_nota ELSE NULL END,',
'    ''SALIDA'', ''NOTA'',',
'    ''S'', :APP_USER, SYSDATE',
'  );',
'',
'  COMMIT;',
'',
'  apex_json.open_object;',
'  apex_json.write(''success'', true);',
'  apex_json.write(''agente'',  l_agente);',
'  apex_json.close_object;',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    ROLLBACK;',
'    apex_json.open_object;',
'    apex_json.write(''success'', false);',
'    apex_json.write(''error'',   SQLERRM);',
'    apex_json.close_object;',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>197781299036365045
);
end;
/
prompt --application/end_environment
begin
wwv_flow_imp.import_end(p_auto_install_sup_obj => nvl(wwv_flow_application_install.get_auto_install_sup_obj, false)
);
commit;
end;
/
set verify on feedback on define on
prompt  ...done
